### ISSUE TITLE
Add files to build Docker containers

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSIplus#10]
It will be useful to test building Docker containers for svFSIplus. Users could then just download an svFSIplus container and run it on an HPC using Singularity.

**Comment by dcodoni** [comment]
Hi @ktbolt 

I created a dockerfile to build a container for svFSIplus solver. The container runs and takes as input 3 variables: type of build (petsc, trilinos, none), the number of tasks and the input file name. 
I also created a workflow file that will build the docker container at each pull request on the main branch and automtically push the container on my dockerhub. Unfortunately it uses my secrets (username and password of dockerhub) and it cannot be merged. 
We should first discuss about having a lab DockerHub account.

David

**Comment by ktbolt** [comment]
@dcodoni We do need to setup a SimVascular account for our containers. 

This [doc](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images) describes how to push docker containers to dockerhub.

**Comment by dcodoni** [comment]
I managed to create a workflow that builds and push container to DockerHub, but I am using my account on DockerHub and this works only on my GitHub fork. It will not work once we merge it to the main repo. When we create a SimVascular account on DockerHub linked to the SimVascular GitHub project, then I think it will work fine.
