### ISSUE TITLE
Move simvascular.github.io documentation to this repository

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSIplus#110]
Currently, our `svFSI-` documentation is in a [different repository](https://github.com/SimVascular/simvascular.github.io/tree/main/documentation/svfsi) in some sub-directories.

I think having documentation and code in the same place would be good. This way, we can easily check/enforce that the documentation gets updated with the code. We can use our Doxygen build/deploy system and easily add existing (and new) markdown pages to the [`HTML` documentation we're already building](https://simvascular.github.io/svFSIplus/index.html). We can link to this `svFSI+` website from the [main website](https://simvascular.github.io/).

The first step would be sorting through the existing documentation. It looks like part of the documentation isn't built currently, and other parts overlap with the documentation in this repository. I think this would also make sense for the other solvers.

Thoughts, @ktbolt, @MatteoSalvador?

**Comment by dcodoni** [comment]
Hi @mrp089,

Shall we close this issue, since we decided already how to handle the documentation?
