### ISSUE TITLE
Remove support for higher-order elements?

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSIplus#145]
### Use Case

The solver currently supports the following types of higher-order elements 
- 10-noded tet
- 20-noded hex
- 27-noded hex
- 8-noded quad,
- 9-noded quad
- 6-noded triangle
- 3-noded line

### Problem

Support for  higher-order elements increases the code size, complexity and testing support.

### Solution

Do we need to support higher-order elements?

### Alternatives considered

Retain support for high-order elements.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by wgyang** [comment]
When a high order mesh is used, the face mesh cannot be represented by vtp file. It is written in an unstructured grid (vtu) file. Currently, svFSIplus uses load_vtp to read face files making high-order cases unsupported. Can read_vtp also takes mshtype as input in addition to face type?
