### ISSUE TITLE
Results are only compared for first field in each test

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSIplus#173]
### Description

When I added the ALE test case in 9146764, I modified the test routine `run_with_reference` to incorporate testing several fields (e.g., pressure and velocity). This is a good idea in theory.

However, for reasons no longer obvious to me, I included this `return` statement if the results pass for a given field:
https://github.com/SimVascular/svFSIplus/blob/25e9186f7ab8d3102ec375d9a58224f565d6b7de/tests/conftest.py#L108-L109

This means that the testing will stop after checking the first field. If there is an error in any other field, it will not be detected.

### Reproduction

Add a bogus field to any of the `fields` arrays in any physics, and the tests will still pass.

### Expected behavior

We should loop over all defined fields for a test case and compare them to the reference. If the field doesn't exist (in simulation or reference), an error should be thrown.

### Additional context

The fix itself is easy: Remove the `return` statement.

However, there are now two problems:
1. Some reference solutions never existed
2. Some fields could have a difference higher than the default tolerance of `1.0e-12`

Problem 1 is somewhat easy to fix. I just need to recompute all the reference solutions that have fields missing and update them. Problem 2 could be spicy since there might be bugs already in the code that we haven't caught (but falsely thought we did). I'll report back.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by mrp089** [comment]
I only started looking into this because I noticed a typo in one of the fields, but the tests seemed to be passing fine:
https://github.com/SimVascular/svFSIplus/blob/372851e39e163cfcb4462c2a5ca98b06337dc058/tests/test_struct.py#L13

**Comment by mrp089** [comment]
Here's an initial overview of what I found after looping over **all** fields in the tests locally. I also opened a pipeline in #175.

Missing results:
```
FAILED test_cmm.py::test_pipe_3d[1] - ValueError: Field Traction not in simulation result
FAILED test_cmm.py::test_pipe_3d[3] - ValueError: Field Traction not in simulation result
FAILED test_cmm.py::test_pipe_3d[4] - ValueError: Field Traction not in simulation result

FAILED test_fluid.py::test_cavity_2d[1] - ValueError: Field Traction not in simulation result
FAILED test_fluid.py::test_cavity_2d[3] - ValueError: Field Traction not in simulation result
FAILED test_fluid.py::test_cavity_2d[4] - ValueError: Field Traction not in simulation result

FAILED test_struct.py::test_LV_Guccione_passive[1] - ValueError: Field Stress not in simulation result
FAILED test_struct.py::test_LV_Guccione_passive[3] - ValueError: Field Stress not in simulation result
FAILED test_struct.py::test_LV_Guccione_passive[4] - ValueError: Field Stress not in simulation result

FAILED test_ustruct.py::test_block_compression[1-P1P1_VMS] - ValueError: Field VonMises_stress not in simulation result
FAILED test_ustruct.py::test_block_compression[3-P1P1_VMS] - ValueError: Field VonMises_stress not in simulation result
FAILED test_ustruct.py::test_block_compression[4-P1P1_VMS] - ValueError: Field VonMises_stress not in simulation result

FAILED test_ustruct.py::test_tensile_adventitia_HGO[1] - ValueError: Field Pressure not in simulation result
```
I can add those outputs to the input files, but the reference solution will most likely be missing them, too.

Different results:
```
FAILED test_cmm.py::test_iliac_artery_variable_wall_props[1] - ValueError: Test failed in field Pressure. Results differ by more than rtol=1e-12 in 30% out of results. Max. abs. differences is 2.5e-06 (rel. 2.6e-11)

FAILED test_fsi.py::test_pipe_3d[3] - ValueError: Test failed in field Pressure. Results differ by more than rtol=1e-12 in 40% out of results. Max. abs. differences is 1.3e-07 (rel. 1.4e-08)
FAILED test_fsi.py::test_pipe_3d[4] - ValueError: Test failed in field Pressure. Results differ by more than rtol=1e-12 in 40% out of results. Max. abs. differences is 1.6e-07 (rel. 1.7e-08)

FAILED test_struct.py::test_LV_Holzapfel_passive[1] - ValueError: Test failed in field Velocity. Results differ by more than rtol=1e-12 in 6% out of results. Max. abs. differences is 6.7e-07 (rel. 6.7e-06)
FAILED test_struct.py::test_LV_Holzapfel_passive[3] - ValueError: Test failed in field Velocity. Results differ by more than rtol=1e-12 in 6% out of results. Max. abs. differences is 6.7e-07 (rel. 6.7e-06)
FAILED test_struct.py::test_LV_Holzapfel_passive[4] - ValueError: Test failed in field Velocity. Results differ by more than rtol=1e-12 in 6% out of results. Max. abs. differences is 6.7e-07 (rel. 6.7e-06)

FAILED test_struct.py::test_block_compression[1] - ValueError: Test failed in field Stress. Results differ by more than rtol=1e-12 in 100% out of results. Max. abs. differences is 3.2e-02 (rel. 1.0e-09)
FAILED test_struct.py::test_block_compression[3] - ValueError: Test failed in field Stress. Results differ by more than rtol=1e-12 in 100% out of results. Max. abs. differences is 4.5e-02 (rel. 1.4e-09)
FAILED test_struct.py::test_block_compression[4] - ValueError: Test failed in field Stress. Results differ by more than rtol=1e-12 in 100% out of results. Max. abs. differences is 1.2e-02 (rel. 3.8e-10)

FAILED test_ustruct.py::test_tensile_adventitia_HGO[3] - ValueError: Test failed in field Velocity. Results differ by more than rtol=1e-12 in 0% out of results. Max. abs. differences is 1.1e-08 (rel. 1.2e-08)
FAILED test_ustruct.py::test_tensile_adventitia_HGO[4] - ValueError: Test failed in field Velocity. Results differ by more than rtol=1e-12 in 14% out of results. Max. abs. differences is 2.5e-08 (rel. 2.7e-08)
```

That's a long list of results that should be identical on my machine to whichever machine computed the reference solution.

I'm particularly worried about the discrepancy in test performance depending on the number of procs:
- `test_cmm.py::test_iliac_artery_variable_wall_props` fails `Pressure` for 1, but passes for 3 and 4 procs
- `test_fsi.py::test_pipe_3d` fails `Pressure` for 3 and 4, but passes for 1 proc
- `test_ustruct.py::test_tensile_adventitia_HGO` fails `Velocity` for 3 and 4, but passes for 1 proc
- `test_struct.py::test_block_compression` fails `Stress` with different values for 1, 3, and 4 procs

@ktbolt, @MatteoSalvador, do you have any thoughts on how to proceed?

**Comment by mrp089** [comment]
For the different physics, only the following fields were (successfully) tested:
- ~~`cep`: Action_potential~~
- `cmm`: Displacement, Stress
- `fluid`: Velocity
- `fsi`: Displacement
- ~~`heats`: Temperature~~
- `stokes`: Pressure
- `struct`: Displacement
- `ustruct`: Displacement

For everything else, we currently have no guarantee that it works as intended. I crossed out the physics, where there was only one field anyway and should not be affected by this issue.

**Comment by MatteoSalvador** [comment]
Thanks @mrp089! For the first set of errors (`Missing results`), I would try to see if those outputs can be actually exported in these test cases and change the `.xml` files (or the tested fields) accordingly. For the second (`Different results`), we probably need to sit down together to see if these absolute differences are actually meaningful. For instance, the worst one is `Stress` in `test_block_compression`, as the difference is in the order of `10e-2`,  but given the normal (high) magnitude of stresses, this might still be a totally reasonable approximation/value for the metric we use.

**Comment by mrp089** [comment]
I agree, @MatteoSalvador, that different tolerances might make sense for primary and derived fields. I was surprised we could test these other fields with `1e-12` (now we know we never actually tested them). But before we lower any tolerances, we have to figure out why we get different results on different machines.

The pipeline ran for [Ubuntu 20](https://github.com/SimVascular/svFSIplus/actions/runs/7649164514/job/20843118014?pr=175), [Ubuntu 22](https://github.com/SimVascular/svFSIplus/actions/runs/7649164514/job/20843118121?pr=175), and [macOS 12](https://github.com/SimVascular/svFSIplus/actions/runs/7649164514/job/20843118219?pr=175). The Ubuntu results are identical. However, macOS and Ubuntu differ in `Stress` for the following tests:
- `test_struct.py::test_block_compression`
- `test_struct.py::test_robin` (which didn't fail locally since the reference was computed on my machine)

Maybe most of this can be explained by a `Stress`-related post-processing bug that only appears under macOS? This could be related to #137 (and #92).

**Comment by ktbolt** [comment]
I compute percentage difference when comparing C++ and Fortran results rather than comparing to an absolute tolerance, an absolute tolerance is not meaningful for all results. It is also good to check that max/min values for a field agree.

For example it is acceptable that pressures differ by 1e-6 if pressure values are in the range [min=83355.9, max=99402.8].
