### ISSUE TITLE
Terminate simulation if max number of Newton iterations is reached by default

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSIplus#192]
### Problem

We currently continue a simulation without an error or warning when the maximum number of Newton iterations is reached. This might wrongly indicate to the user that a time step has converged. 

### Solution

By default, terminate the solution with an error if running into the maximum number of Newton iterations. Let the user define a flag to continue but still throw a warning every time this happens.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
I've changed the message output from
```
FS 1-5  3.673e+01  [5 1.848e+00 1.848e+00 6.685e-02]  !5100 0 99!
MAX NUMBER OF NONLINEAR ITERATIONS REACHED. CHECK CONVERGENCE.
```
to 
```
FS 1-5  3.673e+01  [5 1.848e+00 1.848e+00 6.685e-02]  !5100 0 99!
[svFSIplus] WARNING The number of nonlinear iterations (4) has exceeded the maximum number set by the value of the Add_equation/Max_iterations parameter in the svFSIplus solver input file. 
This may be due to the failure of the linear system solution to convergence.
```

**Comment by ktbolt** [comment]
I have also added a more noticeable indicator of the failure of linear solution convergence from **!** (which I missed for a very long time)

```
FS 1-1  7.374e+00  [0 1.000e+00 1.000e+00 8.630e-02]  !5100 0 99! 
```
 to
```
 FS 1-1  7.374e+00  [0 1.000e+00 1.000e+00 8.630e-02]  !5100 0 99!  WARNING: The linear system solution has not converged
```
