### ISSUE TITLE
Remove _cpp from outputs

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSIplus#199]
### Problem

As a sign that we're moving on with `svFSIplus`, I'd like to remove the automatic appendix `_cpp` from all output files.

### Solution

Run
```
find . -type f -exec sed -i '' 's/_cpp//g' {} +
```
in `Code/Source/svFSI`

### Additional context

@ktbolt, any objections?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@mrp089 No objections, I should have done that before making the repository public.
