### ISSUE TITLE
High order element face mesh cannot be loaded

### ISSUE THREAD

**Issue by wgyang** [SimVascular/svFSIplus#205]
### Description

When a high order mesh is used, the face mesh cannot be represented by vtp file. It should be written in an unstructured grid (vtu) file. svFSIplus uses load_vtp to read face files leading to an error when a high-order element mesh is used, for example, a curved quadratic triangle mesh. The P2 surface meshes used in the block compression test in svFSI-Tests are incorrect as they are written in vtp files. The figure below shows the face vtp file.
![x1_vtp](https://github.com/SimVascular/svFSIplus/assets/16581783/50ac5a2e-220b-4482-a0c7-5a9f4f990b66)

To support true high-order element meshes,  function read_vtp needs to accept mshtype as input in addition to face type when it reads face files.

### Reproduction

A tet10 mesh, svFSI.inp, and svFSI.xml are attached below for testing. 
[tet10_test.zip](https://github.com/SimVascular/svFSIplus/files/14505435/tet10_test.zip)

### Expected behavior

svFSIplus can read and output the high-order meshes it supports.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@wgyang Please upload all of the files needed to run a simulation so I can test.

**Comment by wgyang** [comment]
> @wgyang Please upload all of the files needed to run a simulation so I can test.

I modified my original post to include the mesh and input files.

**Comment by ktbolt** [comment]
The problem was that the `read_vtp()` function was expecting to read a VTP file for some reason. 

I've added a check for a VTU file in`read_vtp()` and added a `load_vtu()` function that works with faces. I also needed to add `vtk_xml_parser` functions to store `vtkUnstructuredGrid` data into a face.

The simulation now runs but svFSIplus results don't match the Fortran results.

**Comment by ktbolt** [comment]
I've fixed several bugs 
- indexing
- array out of bounds
- tet10 2nd derivatives
- C++ code not updated with Fortran bug fix 

A bug fest for sure!

So after fixing the .inp and .xml solver files to have the same parameters the C++ and Fortran code produce the same results.

**Comment by wgyang** [comment]
@ktbolt  Thank you Dave!! I can add this example to the test cases once you merge your fix into the main branch.

**Comment by ktbolt** [comment]
Thank Q @wgyang, allowed me to find several important bugs.
