### ISSUE TITLE
The tests/cases/fluid/pipe_RCR_3d/lumen_inlet.fcs file format is wrong

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSIplus#226]
### Description

The file https://github.com/SimVascular/svFSIplus/blob/main/tests/cases/fluid/pipe_RCR_3d/lumen_inlet.fcs does not have the correct format for a file containing Fourier coefficients
```
    0.0000
    1.0000
    0.000000E+00
    0.000000E+00
    16
   -6.283185E+01    0.000000E+00
    6.263025E+01   -1.868984E-07
   -1.851028E-07    1.979808E-15
   -3.293147E-07    1.821408E-07
    2.967629E-07    4.499564E-17
   -7.134611E-07   -1.729158E-07
   -1.667927E-07    5.199497E-16
   -1.920733E-06    1.597801E-07
    5.066059E-08   -2.587250E-16
    9.364629E-07   -1.435117E-07
   -1.344913E-07    8.999129E-17
   -9.410540E-07    1.250477E-07
    1.921845E-07    2.874722E-17
    9.540060E-07   -1.054107E-07
   -9.547580E-08   -1.106526E-16
    1.016783E-06    8.563008E-08
```

### Reproduction

Look at the file.

### Expected behavior

I think the file format is
```
InitialTime Period
InitialValue1 InitialValue2 ... InitialValue_NDIM 
TimeDerivativeLinearPart1 TimeDerivativeLinearPart2 ... TimeDerivativeLinearPart_NDIM
NumberOfFourierModes
RealPart1 ImaginaryPart1
...
```

### Additional context

Note that README file for this test case is also wrong.

I don't think this has ever been tested.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by dcodoni** [comment]
@ktbolt in the input file the file that is read is not lumen_inlet.fcs but lumen_inlet.flow (which has a format similar to what you mentioned above).
Do you think we could close this issue?

**Comment by ktbolt** [comment]
@dcodoni The README for this test case used to reference `lumen_inlet.fcs` 
```
This example provides two ways of specifying unsteady boundary conditions:

(a) Providing time-dependent data as input using the keyword,

`Temporal values file path: lumen_inlet.flow`

(b) Providing interpolated Fourier coefficients as input using the keyword,

Fourier coefficients file path: lumen_inlet.fcs
```
When I ran the `Fourier coefficients file path` case the solver failed.

It would be good the remove `lumen_inlet.fcs` then.
