### ISSUE TITLE
Move most all documentation to https://simvascular.github.io

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSIplus#228]
### Use Case

It would be good to have a single location for svFSIplus documentation.

### Problem

There are currently two sources of svFSIplus documentation.

1) The primary documentation for all applications is in  https://github.com/SimVascular/simvascular.github.io. I am currently replacing svFSI documentation with svFSIplus documentation. 

2) The other source of documentation is in https://github.com/SimVascular/svFSIplus/tree/main/Documentation/pages. This duplicates a lot of information in 1.

### Solution

I am going to remove https://github.com/SimVascular/svFSIplus/tree/main/Documentation/pages and the `gh-pages` branch. 

I will keep the `building` and `testing` documentation on https://github.com/ktbolt/svFSIplus as README.md files.

I will add a `Developers Guide` section to `https://simvascular.github.io/#documentation`.

### Alternatives considered

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by aabrown100-git** [comment]
I don't feel too strongly, but I tend to agree with Martin. It feels more natural to have the documentation with the code. If someone adds a feature, they can update the documentation in the same pull request, rather than a separate pull request in another repository.

**Comment by MatteoSalvador** [comment]
I also tend to agree with @mrp089 and @aabrown100-git. In this way, features specific to SimVascular, svSolver, svFSI, svOneDSolver and svZeroDSolver can be documented separately. These repositories are large and quite different in terms of the functionality they provide. Furthermore, the documentation can be controlled independently by each research subgroup, and grows better in a distributed way.

**Comment by dcodoni** [comment]
I agree with this last solution @MatteoSalvador proposed. I prefer to have a documentation specific to a repository in the repository itself. I find it easier to update too, avoiding possible confusion.

**Comment by menon-karthik** [comment]
I discussed with @ktbolt yesterday and we agreed on the same solution as @MatteoSalvador mentioned above. We can have code-specific details with each repository. But for end-users who just want to use Simvascular, it might make sense to provide an overview on how to use each solver, format input files, etc. on the Simvascular website since that's supposed to serve as an entry-point for users and it's where the tutorials are (at least for svSolver). 

One concern I have is that anyone who wants to dig slightly beyond just being a user will need to look at documentation in two different places - the user docs on the SV website and the code docs in the repository. Do we have a good solution to that?

**Comment by dcodoni** [comment]
@menon-karthik I do not know if this is relevant, but few times I saw documentation of big project that just point to the git repository through an hyperlink for more details on some parts. Maybe it can be done the same for SV website.

**Comment by ktbolt** [comment]
Thank you @mrp089 @mrp089 @MatteoSalvador @menon-karthik for your input. 

The two levels of documentation approach makes the most sense so we will go with that.

Most of our effort needs to be focused on `user documentation`. This should include 
- theory section 
- file formats
- running the solver
- solver output 
- common problems
- use case examples 
- any implementation details that a user may find useful

The `developer documentation` should be organized well and have sections including
- architecture (if there is one!)
- organization
- important implementation details
- how to modify the code
- doxygen api docs
- building and deployment and testing

I've added a `Developer  Guide` section to the [SimVascular Website](https://github.com/SimVascular/simvascular.github.io) which has most of these. 

We need to reorganize and clean up https://simvascular.github.io/svFSIplus including
- the main page has svFSI rather than svFSIplus
- references a bunch of Fortran svFSI things
- table of contents menu on the wrong side 

to make it useful and nice to look at. 

Doxygen is only useful if the code is commented and commented well, we need to work on that.

**Comment by ktbolt** [comment]
I am going to start cleaning up and reorganizing the `gh-pages` documentation.

**Comment by ktbolt** [comment]
I've cleaned up the `gh-pages` documentation, left the doxygen docs there and moved the other documentation (e.g. build instructions) to the README file

<img width="1056" alt="Screenshot 2024-08-20 at 6 30 28 PM" src="https://github.com/user-attachments/assets/1cfae81c-f8c4-45f7-b477-cf340eb5942b">

**Comment by ktbolt** [comment]
Selecting the `svFSIplus Internal Code Documentation` link in the README brings up the doxygen documentation


<img width="1194" alt="Screenshot 2024-08-20 at 7 00 21 PM" src="https://github.com/user-attachments/assets/e8ff7538-5001-46a5-97e2-f02edaeebdc2">

**Comment by ktbolt** [comment]
Up and running!
