### ISSUE TITLE
Merge Navier-Stokes-Brinkman implementation from Fortran to C++

### ISSUE THREAD

**Issue by JonathanPham** [SimVascular/svFSIplus#236]
### Problem

The [Navier-Stokes-Brinkman equations](https://github.com/fgerosa/svFSI/tree/Contact) were originally implemented by @fgerosa in the Fortran version of svFSI for modeling porous media in her [paper](https://www.sciencedirect.com/science/article/pii/S0045782524001981). We want to merge this implementation into svFSIplus.

### Solution

The Navier-Stokes equations implemented in `fluid.[h/cpp]` should be updated to be Navier-Stokes-Brinkman equations, where the Brinkman component can be turned off or on, depending on the desired physics. If this component is turned off, then we should recover exactly the original Navier-Stokes implementation. If it is turned on, then the simulations should exhibit permeability effects (from the Brinkman term).

There is a permeability parameter used in the Brinkman component. We can set this parameter to have a default value of 0, so that the default physics is Navier-Stokes. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@JonathanPham What is porous media used to model ? Is this for growth and remodeling or heart tissue or something?

**Comment by JonathanPham** [comment]
It can be used to model heart tissue. But Fannie also previously used it as a technique to support fluid-structure-contact modeling.

**Comment by ktbolt** [comment]
So the code has been modified to use this for tissue perfusion and FSI contact?

**Comment by JonathanPham** [comment]
It's been modified for to support FSI contact (although the contact piece still needs to be converted from Fortran to C++). This modification with the Brinkman equations hasn't been used for perfusion before (in the lab), but I can see that as a potential future use case.

**Comment by ktbolt** [comment]
Thanks for the clarification!
