### ISSUE TITLE
svFSIplus does not test the heatF equation

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSIplus#237]
### Description

There is no test for unsteady advection-diffusion (**heatF** equation).

Note that there is also no test for heatF in [svFSI-Tests](https://github.com/SimVascular/svFSI-Tests) so I wonder if the C++ code works.

### Reproduction

Try to test a unsteady advection-diffusion simulation.

### Expected behavior

Add a test for unsteady advection-diffusion (heatF equation).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by zasexton** [comment]
I can help with this

**Comment by ktbolt** [comment]
@zasexton Very good!

**Comment by ktbolt** [comment]
There is in fact a test for the `heatF` equation in https://github.com/SimVascular/svFSIplus/tree/main/tests/cases/fluid/dye_AD, the equation is named `scalarTransport`, missed that, sorry!
