### ISSUE TITLE
When Continue_previous_simulation=1，there is a judegement error.

### ISSUE THREAD

**Issue by Lina-xia** [SimVascular/svFSIplus#243]
### Description

When _Continue_previous_simulation_ is set to 1(true), an error in the judgment of the stop time step _stopTS=nTS=Number_of_time_steps_ and the current time step _cTS_, which caused _l1=1_ and early termination of the simulation.

### Reproduction

For example, in the cases/fluid/dye_AD , run 3 steps first. Then used _Continue_previous_simulation=1_ and _Number_of_time_steps=3_ for the simulation. Theoretically, it should jump out at _cTS=6_, but in fact it jumped out at _cTS=4_.

### Expected behavior

See below.

### Additional context

I set up some output so that I could see where was the error, showing that the wrong judgment in _l1_ caused the jump.
![bug1](https://github.com/user-attachments/assets/4fa91655-0858-4035-86b5-2e00a726bc50)
![bug](https://github.com/user-attachments/assets/b5b603dc-d94a-43be-a5aa-95419bc863b7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@Lina-xia The way the code works is correct.

If you want to continue a simulation then you need to set the `Number_of_time_steps` parameter to the number of time steps the simulation is to continue to run to. I don't think it makes sense to continue the simulation in increments of `Number_of_time_steps`.

The goal is to prevent unexpected behavior of the solver, like accidentally setting the `Continue_previous_simulation` parameter and the solver runs for another 1000 time steps! 

If there is a valid use-case for continuing a simulation in time step increments then a parameter for that can be added. This makes it clear what the behavior of the solver will be.
