### ISSUE TITLE
CMakeList not configured to detect and recompile modified source files

### ISSUE THREAD

**Issue by ignaciobartol** [SimVascular/svFSIplus#246]
### Description

When building the project using `make` (after doing `cmake`), changes made to the source code were not being detected, resulting in new modified files not being used during the build process. This issue can be resolved by adding the `BUILD_ALWAYS TRUE` flag to the `ExternalProject_Add` command in the CMakeLists.txt file. 

### Reproduction

1. Clone the repository.
2. Configure the project using CMake (without the BUILD_ALWAYS TRUE flag in the [ExternalProject_Add(svFSI](https://github.com/SimVascular/svFSIplus/blob/1760590be46dce6623ee2aea5df39736bc42a27a/CMakeLists.txt#L127)).
3. Modify a source file in the Code/Source directory.
4. Run make to build the project.
5. Observe that the modified file is not recompiled.

### Expected behavior

The modified file should be detected by `make` and recompiled. 

### Additional context

I am submitting a PR to solve this small issue if you find it appropiate. Thanks :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@ignaciobartol You need to cd to the `build/svFSI-build` directory for CMake to detect changes to files. This is standard behavior.

**Comment by ignaciobartol** [comment]
Hi @ktbolt, thanks for your quick response and for the clarification. I'll make sure to build from `build/svFSI-build`, I thought cmake was supposed to detect changes from the top-level, but makes sense to not check all the externals every rebuild. I will close the linked PR then. Please feel free to close this issue if you have no further comments.
