### ISSUE TITLE
Solid viscosity default value is 0.9

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/svFSIplus#269]
### Description

If `Solid_viscosity` is not specified in the input file, it's default value is 0.9. This was introduced in [this pull request](https://github.com/SimVascular/svFSIplus/pull/55/files#diff-4f22457f79cb895a90b70ac6497dd3552cb07512e65c94bf5fee2115675ab7a4) (see `Parameters.cpp`). This affects both `struct` and `ustruct`.

### Reproduction

In `sv_struct.cpp` and `ustruct.cpp`, print the value of `mu` to the output. Run either a `struct` or `ustruct` test case, and notice that the value of `mu` is `9.0000000000000002e-01`.

### Expected behavior

The default value of `Solid_viscosity` should be 0.0. If it is not defined in the input file, I think most people would assume it's value is 0.

### Additional context

This may be a cause of slow nonlinear convergence in `ustruct/LV_Guccione_active` test cases (https://github.com/SimVascular/svFSIplus/issues/197). When looking at causes, we had assumed `Solid_viscosity` was 0. There may be a bug in the solid viscosity tangent implementation in `ustruct`, which would cause poor nonlinear convergence is `Solid_viscosity` is nonzero.

UPDATE: After setting `Solid_viscosity` to 0, this test cases still displays slow nonlinear convergence. There must be another bug somewhere.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@aabrown100-git This seems to be a typo, the Fortran code sets the default to 0.0.

**Comment by aabrown100-git** [comment]
Closing this since https://github.com/SimVascular/svFSIplus/pull/270 was merged.
