### ISSUE TITLE
pytest fails when using MPICH due to oversubscribe

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/svFSIplus#281]
### Description

If a user has [MPICH](https://www.mpich.org/) installed on their computer (rather than [Open MPI](https://www.open-mpi.org/doc/)), `pytest` integration tests that use more than one processor fail. This is because the `mpirun` [`--oversubscribe`](https://github.com/SimVascular/svFSIplus/blob/5a688bdf0ac7bd29c76dbc7c9c6ecff045832051/tests/conftest.py#L71) flag is not available with MPICH.

### Reproduction

- Install MPICH. On Mac, I did this with `brew install mpich`
- Try running any integration test using `pytest`. For example, navigate to `tests` folder and run `pytest -v -s -k LV_Guccione_passive`
- Observe the output. The 1 processor case will pass, but the 3 and 4 processor cases will fail immediately with something like below

```
test_struct.py::test_LV_Guccione_passive[3] [mpiexec@Aarons-MBP.attlocal.net] match_arg (lib/utils/args.c:166): unrecognized argument oversubscribe
[mpiexec@Aarons-MBP.attlocal.net] HYDU_parse_array (lib/utils/args.c:181): argument matching returned error
[mpiexec@Aarons-MBP.attlocal.net] parse_args (mpiexec/get_parameters.c:313): error parsing input array
[mpiexec@Aarons-MBP.attlocal.net] HYD_uii_mpx_get_parameters (mpiexec/get_parameters.c:48): unable to parse user arguments
[mpiexec@Aarons-MBP.attlocal.net] main (mpiexec/mpiexec.c:54): error parsing parameters
FAILED

test_struct.py::test_LV_Guccione_passive[4] [mpiexec@Aarons-MBP.attlocal.net] match_arg (lib/utils/args.c:166): unrecognized argument oversubscribe
[mpiexec@Aarons-MBP.attlocal.net] HYDU_parse_array (lib/utils/args.c:181): argument matching returned error
[mpiexec@Aarons-MBP.attlocal.net] parse_args (mpiexec/get_parameters.c:313): error parsing input array
[mpiexec@Aarons-MBP.attlocal.net] HYD_uii_mpx_get_parameters (mpiexec/get_parameters.c:48): unable to parse user arguments
[mpiexec@Aarons-MBP.attlocal.net] main (mpiexec/mpiexec.c:54): error parsing parameters
FAILED
```

### Expected behavior

`pytest` integration tests should ideally work with MPICH.

To be fair, the integration tests don't necessarily need to be run by users on their own machines. However, I think developers often want to run integration tests locally, and they should be able to without having to switch to Open MPI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
@aabrown100-git The svFSIplus documentation states that the program is to be built using OpenMPI. The installers also state that the program is built with a specific OpenMPI version.

**Comment by aabrown100-git** [comment]
@ktbolt Oops didn't realize that! Makes sense, closing this issue now.
